### ISSUE TITLE
'ERROR: Unknown option: ma4' when trying to rebuild compressed RAR under Linux

### ISSUE THREAD

**Issue by jaloji** [srrDB/pyrescene#19]
Hi,
I'm trying to rebuild compressed rar under Debian, I've used preprardir.py -b /app/rarlinux-master/ /app/rarv/
All the RAR version come from: https://github.com/dryes/rarlinux/archive/refs/heads/master.zip

Inside my rarv dir I've:
```
root@pyautorescene:/input# ls -lia /app/rarv
15121 -rwxrwxrwx 1 root root  95456 Dec 29  1997 1997-12-29_rar202
15122 -rwxrwxrwx 1 root root 121172 Mar 24  1999 1999-03-24_rar250
15123 -rwxrwxrwx 1 root root 403092 Sep 21  1999 1999-09-21_rar260b5
15124 -rwxrwxrwx 1 root root 403708 Sep 29  1999 1999-09-29_rar260b6
15125 -rwxrwxrwx 1 root root 404876 Oct 18  1999 1999-10-18_rar260
15126 -rwxrwxrwx 1 root root 405396 Jun 21  2000 2000-06-21_rar271
15127 -rwxrwxrwx 1 root root 252908 Mar  2  2001 2001-03-02_rar280
15128 -rwxrwxrwx 1 root root 232768 Jul 28  2001 2001-07-28_rar290b1
15129 -rwxrwxrwx 1 root root 261360 Aug 14  2001 2001-08-14_rar290b2
15130 -rwxrwxrwx 1 root root 261104 Sep  7  2001 2001-09-07_rar290
15131 -rwxrwxrwx 1 root root 307608 Jan 28  2002 2002-01-28_rar300b2
15132 -rwxrwxrwx 1 root root 650792 Apr 21  2002 2002-04-21_rar300b6
15133 -rwxrwxrwx 1 root root 650792 May 14  2002 2002-05-14_rar300
15134 -rwxrwxrwx 1 root root 663012 Oct 16  2002 2002-10-16_rar310b1
15135 -rwxrwxrwx 1 root root 663140 Oct 23  2002 2002-10-23_rar310b2
15136 -rwxrwxrwx 1 root root 290536 Dec 19  2002 2002-12-19_rar310
15137 -rwxrwxrwx 1 root root 291592 Jan 15  2003 2003-01-15_rar311
15138 -rwxrwxrwx 1 root root 289904 Mar  9  2003 2003-03-09_rar320b1
15139 -rwxrwxrwx 1 root root 289936 Mar 17  2003 2003-03-17_rar320b2
15140 -rwxrwxrwx 1 root root 290096 Apr  5  2003 2003-04-05_rar320b3
15141 -rwxrwxrwx 1 root root 290224 Apr 21  2003 2003-04-21_rar320b4
15142 -rwxrwxrwx 1 root root 290352 May 15  2003 2003-05-15_rar320
15143 -rwxrwxrwx 1 root root 298320 Nov 14  2003 2003-11-14_rar330b1
15144 -rwxrwxrwx 1 root root 298352 Dec  6  2003 2003-12-06_rar330b3
15145 -rwxrwxrwx 1 root root 298352 Dec 20  2003 2003-12-20_rar330b4
15146 -rwxrwxrwx 1 root root 298320 Jan  9  2004 2004-01-09_rar330b5
15147 -rwxrwxrwx 1 root root 298320 Jan 22  2004 2004-01-22_rar330
15148 -rwxrwxrwx 1 root root 300752 Jun 20  2004 2004-06-20_rar340b1
15149 -rwxrwxrwx 1 root root 301200 Jul  6  2004 2004-07-06_rar340b2
15150 -rwxrwxrwx 1 root root 302672 Aug 21  2004 2004-08-21_rar340b5
15151 -rwxrwxrwx 1 root root 302160 Sep  9  2004 2004-09-09_rar340
15152 -rwxrwxrwx 1 root root 302704 Nov  2  2004 2004-11-02_rar341
15153 -rwxrwxrwx 1 root root 302928 Mar 31  2005 2005-03-31_rar350b1
15154 -rwxrwxrwx 1 root root 301776 Aug  3  2005 2005-08-03_rar350
15155 -rwxrwxrwx 1 root root 302032 Oct  7  2005 2005-10-07_rar351
15156 -rwxrwxrwx 1 root root 329212 Aug  4  2006 2006-08-04_rar360
15157 -rwxrwxrwx 1 root root 342240 May 22  2007 2007-05-22_rar370
15158 -rwxrwxrwx 1 root root 345504 Sep 20  2007 2007-09-20_rar371
15159 -rwxrwxrwx 1 root root 348612 Jul 10  2008 2008-07-10_rar380b3
15160 -rwxrwxrwx 1 root root 339360 Sep 16  2008 2008-09-16_rar380
15161 -rwxrwxrwx 1 root root 357472 Aug 16  2009 2009-08-16_rar390
15162 -rwxrwxrwx 1 root root 357472 Dec 12  2009 2009-12-12_rar391
15163 -rwxrwxrwx 1 root root 357496 Feb 10  2010 2010-02-10_rar392
15164 -rwxrwxrwx 1 root root 357496 Mar 15  2010 2010-03-15_rar393
15165 -rwxrwxrwx 1 root root 376956 Nov 26  2010 2010-11-26_rar400b2
15166 -rwxrwxrwx 1 root root 376956 Dec 17  2010 2010-12-17_rar400b3
15167 -rwxrwxrwx 1 root root 376956 Jan  4  2011 2011-01-04_rar400b4
15168 -rwxrwxrwx 1 root root 376956 Jan 23  2011 2011-01-23_rar400b5
15169 -rwxrwxrwx 1 root root 376956 Feb 20  2011 2011-02-20_rar400b7
15170 -rwxrwxrwx 1 root root 373976 Mar  2  2011 2011-03-02_rar400
15171 -rwxrwxrwx 1 root root 381052 May 10  2011 2011-05-10_rar401b1
15172 -rwxrwxrwx 1 root root 373976 May 28  2011 2011-05-28_rar401
15173 -rwxrwxrwx 1 root root 391140 Oct  3  2011 2011-10-03_rar410b1
15174 -rwxrwxrwx 1 root root 391140 Oct 20  2011 2011-10-20_rar410b2
15175 -rwxrwxrwx 1 root root 391140 Nov 10  2011 2011-11-10_rar410b3
15176 -rwxrwxrwx 1 root root 391140 Nov 22  2011 2011-11-22_rar410b4
15177 -rwxrwxrwx 1 root root 391140 Dec 15  2011 2011-12-15_rar410b5
15178 -rwxrwxrwx 1 root root 375904 Jan  9  2012 2012-01-09_rar410
15179 -rwxrwxrwx 1 root root 375904 Feb 17  2012 2012-02-17_rar411
15180 -rwxrwxrwx 1 root root 391204 May  2  2012 2012-05-02_rar420b1
15181 -rwxrwxrwx 1 root root 395300 May 13  2012 2012-05-13_rar420b2
15182 -rwxrwxrwx 1 root root 399396 May 27  2012 2012-05-27_rar420b3
15183 -rwxrwxrwx 1 root root 384224 Jun  9  2012 2012-06-09_rar420
15184 -rwxrwxrwx 1 root root 514084 Apr 28  2013 2013-04-28_rar500b1
15185 -rwxrwxrwx 1 root root 514084 Apr 30  2013 2013-04-30_rar500b2
15186 -rwxrwxrwx 1 root root 510020 May 13  2013 2013-05-13_rar500b3
15187 -rwxrwxrwx 1 root root 510020 May 30  2013 2013-05-30_rar500b4
15188 -rwxrwxrwx 1 root root 507700 Jun 18  2013 2013-06-18_rar500b5
15189 -rwxrwxrwx 1 root root 507700 Jul  3  2013 2013-07-03_rar500b6
15190 -rwxrwxrwx 1 root root 511796 Jul 25  2013 2013-07-25_rar500b7
15191 -rwxrwxrwx 1 root root 511796 Aug  6  2013 2013-08-06_rar500b8
15192 -rwxrwxrwx 1 root root 488432 Aug 22  2013 2013-08-22_rar500
15193 -rwxrwxrwx 1 root root 488464 Dec  1  2013 2013-12-01_rar501
15194 -rwxrwxrwx 1 root root 525296 Jun 10  2014 2014-06-10_rar510
15195 -rwxrwxrwx 1 root root 525296 Aug 27  2014 2014-08-27_rar511
15196 -rwxrwxrwx 1 root root 525296 Aug 27  2014 2014-08-27_rar511b1
15197 -rwxrwxrwx 1 root root 529392 Oct  5  2014 2014-10-05_rar520b1
15198 -rwxrwxrwx 1 root root 529392 Oct 30  2014 2014-10-30_rar520b2
15199 -rwxrwxrwx 1 root root 529392 Nov  3  2014 2014-11-03_rar520b3
15200 -rwxrwxrwx 1 root root 529392 Dec  2  2014 2014-12-02_rar520
15201 -rwxrwxrwx 1 root root 529392 Jan 30  2015 2015-01-30_rar521b1
15202 -rwxrwxrwx 1 root root 529392 Jan 31  2015 2015-01-31_rar521b2
15203 -rwxrwxrwx 1 root root 529392 Feb 15  2015 2015-02-15_rar521
15204 -rwxrwxrwx 1 root root 529392 Jul 29  2015 2015-07-29_rar530b1
15205 -rwxrwxrwx 1 root root 533488 Aug 11  2015 2015-08-11_rar530b2
15206 -rwxrwxrwx 1 root root 533488 Sep  9  2015 2015-09-09_rar530b3
15207 -rwxrwxrwx 1 root root 533488 Sep 13  2015 2015-09-13_rar530b4
15208 -rwxrwxrwx 1 root root 533488 Oct 26  2015 2015-10-26_rar530b5
15209 -rwxrwxrwx 1 root root 533488 Nov  2  2015 2015-11-02_rar530b6
15210 -rwxrwxrwx 1 root root 533488 Nov 18  2015 2015-11-18_rar530
15211 -rwxrwxrwx 1 root root 537584 May 16  2016 2016-05-16_rar540b1
15212 -rwxrwxrwx 1 root root 537584 May 30  2016 2016-05-30_rar540b2
15213 -rwxrwxrwx 1 root root 537584 Jul  7  2016 2016-07-07_rar540b3
15214 -rwxrwxrwx 1 root root 537584 Aug 13  2016 2016-08-13_rar540b4
15215 -rwxrwxrwx 1 root root 537584 Aug 14  2016 2016-08-14_rar540
15216 -rwxrwxrwx 1 root root 541648 Apr 24  2017 2017-04-24_rar550b1
15217 -rwxrwxrwx 1 root root 541648 May  5  2017 2017-05-05_rar550b2
15218 -rwxrwxrwx 1 root root 541648 Jun 12  2017 2017-06-12_rar550b3
15219 -rwxrwxrwx 1 root root 541648 Jun 30  2017 2017-06-30_rar550b4
15220 -rwxrwxrwx 1 root root 541648 Jul 22  2017 2017-07-22_rar550b5
15221 -rwxrwxrwx 1 root root 541648 Jul 25  2017 2017-07-25_rar550b6
15222 -rwxrwxrwx 1 root root 541648 Aug 11  2017 2017-08-11_rar550
17808 drwxrwxrwx 1 root root     48 Sep 12 06:50 SRR-86io73co
17810 drwxrwxrwx 1 root root     48 Sep 12 06:50 SRR-ipr60ujj
 5099 drwxrwxrwx 1 root root     96 Sep 12 15:47 tmp
```

There is problem like 32bits binaries on 64bits system like I saw in another issue, so I've do this:
```
dpkg --add-architecture i386
apt update
apt-get install libc6-i386 lib32stdc++6 lib32z1 lib32ncurses6
```

But if I try to rebuild something I've this:
```
root@pyautorescene:/input# srr.py test.srr -z /app/rarv/ -t /app/rarv/tmp/

ERROR: Unknown option: ma4
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/pyReScene-0.7-py3.9.egg/rescene/rar.py", line 1395, in __init__
    self._rarstream = open(rfile, mode="rb")
FileNotFoundError: [Errno 2] No such file or directory: '/app/rarv/tmp/SRR-s5b09v1h/pyReScene_compressed.rar'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/pyReScene-0.7-py3.9.egg/rescene/srr.py", line 605, in main
    parser.exit(manage_srr(options, infolder, infiles, working_dir))
  File "/usr/local/lib/python3.9/dist-packages/pyReScene-0.7-py3.9.egg/rescene/srr.py", line 315, in manage_srr
    rescene.reconstruct(infiles[0], in_folder, out_folder, save_paths,
  File "/usr/local/lib/python3.9/dist-packages/pyReScene-0.7-py3.9.egg/rescene/main.py", line 1331, in reconstruct
    srcfs = get_rar_data_object(block, blocks, src,
  File "/usr/local/lib/python3.9/dist-packages/pyReScene-0.7-py3.9.egg/rescene/main.py", line 1721, in get_rar_data_object
    compressed_rar_file_factory(block, blocks, src, in_folder, hints,
  File "/usr/local/lib/python3.9/dist-packages/pyReScene-0.7-py3.9.egg/rescene/main.py", line 2048, in compressed_rar_file_factory
    return CompressedRarFile(block, blocks, src,
  File "/usr/local/lib/python3.9/dist-packages/pyReScene-0.7-py3.9.egg/rescene/main.py", line 2173, in __init__
    self.good_rar = self.search_matching_rar_executable(
  File "/usr/local/lib/python3.9/dist-packages/pyReScene-0.7-py3.9.egg/rescene/main.py", line 2428, in search_matching_rar_executable
    found = try_rar_executable(rar, args, old)
  File "/usr/local/lib/python3.9/dist-packages/pyReScene-0.7-py3.9.egg/rescene/main.py", line 2353, in try_rar_executable
    with RarStream(out, compressed=True, packed_file_name=pfn) as rs:
  File "/usr/local/lib/python3.9/dist-packages/pyReScene-0.7-py3.9.egg/rescene/rarstream.py", line 76, in __init__
    if not middle and not _check(first_rar):
  File "/usr/local/lib/python3.9/dist-packages/pyReScene-0.7-py3.9.egg/rescene/rarstream.py", line 44, in _check
    rar_reader = rar.RarReader(first_rar)
  File "/usr/local/lib/python3.9/dist-packages/pyReScene-0.7-py3.9.egg/rescene/rar.py", line 1397, in __init__
    raise ArchiveNotFoundError(err)
rescene.rar.ArchiveNotFoundError: [Errno 2] No such file or directory: '/app/rarv/tmp/SRR-s5b09v1h/pyReScene_compressed.rar'
SRR file created with pyReScene Auto 0.7.
Re-creating RAR file: test.rar
Trying to rebuild compressed file test.sub.
Grabbing large enough data piece size for testing.
Trying 2010-02-10 3.92.
Something went wrong executing Rar.exe:
Command line option error
Unexpected Error: [Errno 2] No such file or directory: '/app/rarv/tmp/SRR-s5b09v1h/pyReScene_compressed.rar'
```

Anyway the version needed for this is 64bit...
```
2010-02-10_rar392:   ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 2.6.8, stripped
```

So what is the problem here ?

**Comment by itzoke** [comment]
It seems that the `-ma4` option is set incorrectly. This option should only be set on rar versions 5+.

**Comment by itzoke** [comment]
@jaloji, could you try with branch `bugfix/issue-19` to see if that makes any difference for you?

https://github.com/srrDB/pyrescene/tree/bugfix/issue-19

**Comment by jaloji** [comment]
@itzoke No same error

**Comment by itzoke** [comment]
Which srr is it? If you don't want to divulge that I should be able to create something to try to reproduce your error using the timestamp of the stored file.

Something like this should produce sufficient information
```
srr.py -e <srr-file> | awk '/Rar name:/ {gsub(/.+\./, "", $3); print} /FTIME/ {print} /FILE_NAME/ {sub(/.+\./, "", $2); print}'
```

**Comment by itzoke** [comment]
Including a rar 7 version in the rars folder makes this work for me (on the bugfix/issue-19 branch). So that may be a workaround for now...

**Comment by jaloji** [comment]
@itzoke Ok I would like to try but https://github.com/dryes/rarlinux/archive/refs/heads/master.zip don't have them

**Comment by itzoke** [comment]
You can grab it using `wget ftp://ftp.rarlab.com/rar/rarlinux-x64-701.tar.gz`

**Comment by jaloji** [comment]
Ok it give me:

```
/app/rarv/2005-10-07_rar351: error while loading shared libraries: libstdc++.so.5: cannot open shared object file: No such file or directory

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/pyReScene-0.7-py3.9.egg/rescene/srr.py", line 605, in main
    parser.exit(manage_srr(options, infolder, infiles, working_dir))
  File "/usr/local/lib/python3.9/dist-packages/pyReScene-0.7-py3.9.egg/rescene/srr.py", line 315, in manage_srr
    rescene.reconstruct(infiles[0], in_folder, out_folder, save_paths,
  File "/usr/local/lib/python3.9/dist-packages/pyReScene-0.7-py3.9.egg/rescene/main.py", line 1331, in reconstruct
    srcfs = get_rar_data_object(block, blocks, src,
  File "/usr/local/lib/python3.9/dist-packages/pyReScene-0.7-py3.9.egg/rescene/main.py", line 1721, in get_rar_data_object
    compressed_rar_file_factory(block, blocks, src, in_folder, hints,
  File "/usr/local/lib/python3.9/dist-packages/pyReScene-0.7-py3.9.egg/rescene/main.py", line 2048, in compressed_rar_file_factory
    return CompressedRarFile(block, blocks, src,
  File "/usr/local/lib/python3.9/dist-packages/pyReScene-0.7-py3.9.egg/rescene/main.py", line 2173, in __init__
    self.good_rar = self.search_matching_rar_executable(
  File "/usr/local/lib/python3.9/dist-packages/pyReScene-0.7-py3.9.egg/rescene/main.py", line 2428, in search_matching_rar_executable
    found = try_rar_executable(rar, args, old)
  File "/usr/local/lib/python3.9/dist-packages/pyReScene-0.7-py3.9.egg/rescene/main.py", line 2347, in try_rar_executable
    _fire(MsgCode.MSG, message=RETURNCODE[compress.returncode])
KeyError: 127
Re-creating RAR file: whipit_xvid-cd1.rar
Trying to rebuild compressed file whipit_xvid-cd1.sub.
Grabbing large enough data piece size for testing.
Trying 2010-02-10 3.92.
Trying 2009-12-12 3.91.
Trying 2009-08-16 3.90.
Trying 2008-09-16 3.80.
Trying 2008-07-10 3.80.
Trying 2007-09-20 3.71.
Trying 2007-05-22 3.70.
Trying 2006-08-04 3.60.
Trying 2005-10-07 3.51.
Something went wrong executing Rar.exe:
Unexpected Error: 127
```

**Comment by itzoke** [comment]
The shared library error seems to be another issue. But I think I managed to solve the original issue with the unknown `-ma4` flag in the latest commit to the bugfix/issue-19 branch.

**Comment by jaloji** [comment]
@itzoke Yes it's so weird, I don't know if its normal or what but on Windows it can rebuild it directly without trying all version...

**Comment by itzoke** [comment]
Could you try with commit 094f8cb2b8c7a1573c4cf8d4cb90f620371644a8 and see if you get the same result?

**Comment by jaloji** [comment]
@itzoke I've never done that before, what I've done:

```
wget https://github.com/srrDB/pyrescene/archive/094f8cb.zip
```

Give the exact same error

**Comment by itzoke** [comment]
Ok, then it's not something introduced by the forced `-ma4` option for compressed rars.

You could've just ran `git checkout 094f8cb`

**Comment by jaloji** [comment]
Ok so I can try with master branch again ?

**Comment by itzoke** [comment]
Or the bugfix/issues-19 branch (which should fix the `-ma4` error)

**Comment by jaloji** [comment]
@itzoke With master it didn't try every RAR versions, I just use the issue-19, it try every version except for 4 etc... no m4a error but still doesn't work...

**Comment by itzoke** [comment]
It seems that it's another issue then. Not all compressed rars can be recreated. Which subs are you trying to recreate?

**Comment by jaloji** [comment]
@itzoke I know that, but what I can't understand is why I can recreate it on Windows but not on Linux...

I will delete this after your answer: Whip.It.2009.FRENCH.BDRiP.XviD-SURViVAL

**Comment by itzoke** [comment]
I have no idea why that may be...

**Comment by jaloji** [comment]
@itzoke Can it be possible that its more a problem between x32 and x64 different version I've saw that preprardir don't seem to make a different location for each ?

**Comment by itzoke** [comment]
Seems that the old `-md[A-G]` finally was removed in 7.00 (and silently used/ignored on 5.x and 6.x). I think you can remove the 7.x versions if your main usage is video/subs as 7.00 dropped support for the mandatory rar4 format. This makes it highly unlikely that they are used for that.

As a conclusion on the file not recreating on linux but on windows. For now I'll think we'll just have to accept that this is the case. For all we know this can be caused by slightly different internal workings on the different os releases of the rar versions themselves.

**Comment by jaloji** [comment]
@itzoke Ok I see, thank you for your help but it was my first trying to rebuild compressed rar on linux so... not very encouraging....

**Comment by itzoke** [comment]
Seems you just caught one of the odd ones... :/

**Comment by jaloji** [comment]
@itzoke Ok just to keep you informed I separated the x64 and x86 versions, deleted the 7 versions, launched preprardir -b for the x64 versions in first the scripts to search to the end and tell me No Good version found. So I relaunch prerprardir for x86 -b and this time just launched we will say that version 2.71 is all planted I will delete it and see what it gives
